apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: authenticator
  name: authenticator
spec:
  replicas: 1
  selector:
    matchLabels:
      run: authenticator
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        run: authenticator
    spec:
      hostname: authenticator
      containers:
        - name: authenticator
          tty: true
          image: latonaio/authenticator
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1323

---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: authenticator
  name: authenticator
spec:
  selector:
    run: authenticator
  type: NodePort
  ports:
    - port: 30103
      protocol: TCP
      targetPort: 1323
      nodePort: 30103
---
