apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: ui-authenticator-for-omotebako
  name: ui-authenticator-for-omotebako
spec:
  replicas: 1
  selector:
    matchLabels:
      run: ui-authenticator-for-omotebako
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        run: ui-authenticator-for-omotebako
    spec:
      hostname: ui-authenticator-for-omotebako
      containers:
        - name: ui-authenticator-for-omotebako
          tty: true
          image: latonaio/authenticator
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1323

---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: ui-authenticator-for-omotebako
  name: ui-authenticator-for-omotebako
spec:
  selector:
    run: ui-authenticator-for-omotebako
  type: NodePort
  ports:
    - port: 30103
      protocol: TCP
      targetPort: 1323
      nodePort: 30103
---