version: "3"
services:
  mysql:
    image : mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./misc/config.cnf:/etc/mysql/conf.d/config.cnf
      - ./misc:/docker-entrypoint-initdb.d/
    environment:
      TERM: xterm
      APP_ENV: dev
      MYSQL_USER: DB_USER_NAME
      MYSQL_PASSWORD: DB_USER_PASSWORD
      MYSQL_DATABASE: Authenticator
      MYSQL_ROOT_PASSWORD: root
    container_name: mysql

  authenticator:
    links:
      - mysql
    command: make statik
    build:
      context: .
      dockerfile: ./build/Dockerfile
    ports:
    - "1323:1323"
